package com.modular.ws.client.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-10-25T10:42:28.267-03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "MensajeriaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MensajeriaSoap {

    @WebMethod(operationName = "EnvioSMS", action = "http://tempuri.org/EnvioSMS")
    @RequestWrapper(localName = "EnvioSMS", targetNamespace = "http://tempuri.org/", className = "com.test.ws.client.EnvioSMS")
    @ResponseWrapper(localName = "EnvioSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.test.ws.client.EnvioSMSResponse")
    @WebResult(name = "EnvioSMSResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String envioSMS(
        @WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/")
        java.lang.String mensaje,
        @WebParam(name = "celular", targetNamespace = "http://tempuri.org/")
        java.lang.String celular
    );

    @WebMethod(operationName = "CONSULTA", action = "http://tempuri.org/CONSULTA")
    @RequestWrapper(localName = "CONSULTA", targetNamespace = "http://tempuri.org/", className = "com.test.ws.client.CONSULTA")
    @ResponseWrapper(localName = "CONSULTAResponse", targetNamespace = "http://tempuri.org/", className = "com.test.ws.client.CONSULTAResponse")
    public void consulta(
        @WebParam(name = "SMS_ID", targetNamespace = "http://tempuri.org/")
        int smsID,
        @WebParam(name = "sms_fecha", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar smsFecha,
        @WebParam(name = "sms_mensaje_id", targetNamespace = "http://tempuri.org/")
        int smsMensajeId
    );
}
